### ISSUE TITLE
Money or Investment Strategies?

### ISSUE THREAD

**Issue by serapath** [azer/notebook#2]
Hey :-)

Just found your notebook repository.
Super sweet and a lot of very inspirational stuff.

Had to check out the notes about money, but figured they are not really about money itself.
Maybe it's not too interesting, but I am also maintaining my thoughts about `economy`, which includes thoughts about money.
My understanding of money in a more abstract sense I try to put into an issue to describe  my ideal version of money - not what we actually have today.
https://github.com/serapath/economy/issues/2

**Comment by azer** [comment]
Cool, I'm reading it.
