### ISSUE TITLE
Translation fix

### ISSUE THREAD

**Issue by ancs** [azer/notebook#3]
I'm an Indonesian and there's some word that the meaning in english is incorrect and vice versa, there's also some word's that you probably missprounounced. I've corrected it for you.

> I wrote some of my tips in italics for you. Anyway, good luck.

## Bahasa

* **yes** iya
* **no** enggak/tidak | _type in enggak into google translate so you know hot it's should be pronounced_
* **cool** Anjas/wow | _I don't know in Bali, but in my city (Jakarta), people uses wow instead of anjas_
* **dog** Anjing | _The word anjing has some negative meaning to it, it's like saying someone is a pig, so I recommend you to just not say it._
* **thank you** Terima kasih
* **how are you?** Apa kabar
* **Good** Baik/bagus
* **No good** Enggak/tidak baik
* **Beautiful** bagus/indah
* **good morning** selamat pagi
* **good night** selamat malam
* **delicious** mantap
* **how much?** berapa
* **this** ini
* **apa** what?
* **what is this?** ini apa?
* **where** kemana
* **mau kemana** where are you going to?
* **more** tambah/lagi/lebih
* **do you have water?** kamu ada air? | _aqua is a brand name, it doesn't mean water, **air** means water._
* **expensive** mahal
* **take care** hati hati
* **finish*** udah
* **ayo** lets'go

**Comment by ancs** [comment]
The only thing you got wrong in numbers is seven.

It's not _tuju_, it's _tujuh_, with an h.

**Comment by azer** [comment]
thanks, fixed!
